# ===============================================
# CONFIGURACAO DO SERVIDOR
# ===============================================
server.port=8081

spring.application.name=orcana-microservico-email


# ===============================================
# CONFIGURACAO DO BANCO DE DADOS (MySQL)
# ===============================================
#spring.datasource.url=${DB_URL}
#spring.datasource.driver-class-name=${DB_DRIVER}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}
#spring.jpa.database-platform=${DB_PLATFORM}



# Configuracoes de logging para SQL
logging.level.org.springframework.jdbc.datasource.init=DEBUG
logging.level.org.springframework.boot.autoconfigure.sql.init=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Configuracao de inicializacao do banco
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false
spring.jpa.hibernate.ddl-auto=update

# Logs para confirmar a criacao das tabelas
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================================
# CONFIGURACAO DE E-MAIL (BREVO / SENDINBLUE)
# ===============================================

# Endereco do servidor SMTP do Brevo
spring.mail.host=smtp-relay.brevo.com

# Porta para conexao segura (TLS)
spring.mail.port=587

# Seu e-mail de login no Brevo
spring.mail.username=${BREVO_USER}

# Sua chave/senha SMTP v3 fornecida pelo Brevo
spring.mail.password=${BREVO_PASSWORD}

# Propriedades adicionais para autenticacao e seguranca
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true


# ===============================================
# CONFIGURACAO DO RABBITMQ
# ===============================================
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:myuser}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:secret}

# ===============================================
# CONFIGURACAO DO BROKER (EXCHANGE E FILA)
# ===============================================
broker.exchange.name=${BROKER_EXCHANGE_NAME:orcana.email.exchange}
broker.queue.name=${BROKER_QUEUE_NAME:orcana.email.queue}
broker.routing.key=${BROKER_ROUTING_KEY:orcana.email.send}

# ===============================================
# CONFIGURACAO DE DESSERIALIZACAO JSON
# ===============================================
spring.rabbitmq.listener.simple.default-requeue-rejected=false
spring.rabbitmq.listener.simple.prefetch=1
spring.rabbitmq.template.retry.enabled=false
