name: CD - Deploy

on:
  workflow_run:
    workflows: ["CI - Build e Testes"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker image
        run: docker pull vivisds12/exemplo-actions:latest

      - name: Stop Docker container
        run: docker stop exemplo-actions || true

      - name: Remove Docker container
        run: docker rm exemplo-actions || true

      - name: Run Docker container
        run: docker run --name exemplo-actions -d -p 8080:8080 vivisds12/exemplo-actions:latest